package main;

public class Practice {

    public static void main(String[] args) {
        System.out.println("HELLO, IM LIKE CONSOLE.LOG");
    }

}

/*
JAVA HAS CLASSES, WHICH IS A CONTAINER FOR THE RELATED METHODS.
A METHOD IS A FUNCTION THAT IS PART OF A CLASS.
WHEN A FUNCTION EXISTS OUTSIDE A CLASS, JUST CALL IT A FUNCTION.

------------      BASIC ANATOMY     ----------


WE USE CLASSES TO ORGANIZE OUR CODE.
EVERY JAVA PROGRAM SHOULD CONTAIN AT LEAST ONE CLASS THAT CONTAINS THE MAIN METHOD.

USE PASCAL NAMING CONVENTION ON CLASSES.
(FIRST LETTER ON EVERY WORD CAPITALIZED)

LIKE JS, USE CAMEL CASING WITH METHODS.

EX:
    class Main {
        void main() {
            ...
         }
     }


WHEN WRITING OUT JAVA METHODS, START OUT WITH THE RETURN TYPE.
VOID METHODS RETURNS NOTHING.

FOLLOWING IS THE DESCRIPTIVE NAME OF THE FUNCTION.
LIKE JS, PARAMETERS GO IN THE ()

EX:
    VOID METHOD_NAME(PARAMETERS) {
        ... CODE GOES HERE ... ;
    }

EVERY JAVA PROGRAM NEEDS A MAIN METHOD. THIS IS THE ENTRY POINT FOR OUR PROGRAM.
EVERY TIME WE EXECUTE OUR PROGRAM, THE MAIN METHOD IS CALLED AND THE CODE IN THE MAIN
METHOD IS EXECUTED.

------------------     ACCESS MODIFIER    -----------------------------------

ALL METHODS NEED AN ACCESS MODIFIER.
AN ACCESS MODIFIER IS A KEYWORD THAT DETERMINES IF OTHER CLASSES AND METHODS IN THE PROGRAM
CAN ACCESS THESE CLASSES/METHODS.

EX: PUBLIC, PRIVATE, PROTECTED, DEFAULT

------------------   VERY BASIC EXAMPLE OF A PUBLIC VOID JAVA METHOD   ----------------


PUBLIC CLASS MAIN {
    PUBLIC STATIC VOID MAIN(STRING[] ARGS) {
        ...
     }
}

-------------------------------------------------
SHORTHCUT: TYPE IN sout AND ENTER TO GET System.out.println();
System.out.println() IS BASICALLY JAVA'S VERSION OF JS'S CONSOLE.LOG
IT PRINTS YOUR STRING MESSAGE TO THE TERMINAL.



 */
